version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    
    steps:
      - checkout
      - run:
          command: chmod 777 ./app
      - run:
           command: chmod +x ./gradlew           
      - run:              
           command: ./gradlew build 
      - run:              
           command: |
                    mkdir -p ~/artifacts 
                    cp /home/circleci/project/app/build/outputs/apk/debug/app-debug.apk ~/artifacts

      - store_artifacts:
          path: /