version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    working_directory: /tmp
    steps:
      - checkout
      - run:
          command: chmod 777 ./app
      - run:
           command: chmod +x ./gradlew           
      - run:              
           command: ./gradlew build 

      - store_artifacts:
          path: /tmp/artifacts